version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      # Mounts the backend source code for hot-reloading
      - ./backend:/usr/src/app
      # Anonymous volume to persist node_modules, preventing them from being overwritten
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    # Run the seed script then start the application
    command: sh -c "npm run seed && npm run dev"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mounts the frontend source code for hot-reloading
      - ./frontend:/usr/src/app
      # Anonymous volume to persist node_modules
      - /usr/src/app/node_modules
    environment:
      # Ensures the frontend can communicate with the backend container
      - REACT_APP_API_URL=http://localhost:4000/api
      # Enables hot-reloading to work correctly inside Docker
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

 
networks:
  app-network:
    driver: bridge